### ISSUE TITLE
Travis Bug?

### ISSUE THREAD

**Issue by JDPailleux** [CHPS-M1-PRIME-NUMBERS/Prime_numbers#10]
Sur le dernier commit sur master, Travis indique une erreur alors qu'il compile chez maxence et moi-même. 
Est-ce normal?

**Comment by Nambrok** [comment]
Oui, c'est parce que Travis n'a pas la bibliothèque NTL qui est utilisé par AKS, vous devez sûrement l'avoir installé sur votre machine et le CMake l'a correctement intégré. Je jetterai un oeil sur ce problème dans quelques temps.

**Comment by Emaltard** [comment]
On oublie Travis, problèmes d'integration de GMP/NTL.
